[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
  "python3 -m playwright install --with-deps"
]

[phases.start]
cmd = "python3 billion_club.py"